#!/bin/bash

#**************************************************************************************************************
#	Filename:		CopyOutputFiles.sh
#	Author:		Victoria Trenton
#	Last Update:	July 24,2012
#
# This script moves the LHE (unweighted_events.lhe) and ROOT (unweighted_events.root) files
# for events generated by MadGraph.
#
# Make this script executable by typing
#	chmod u+x CopyOutputFiles.sh		(for the user) or
#	chmod +x CopyOutputFiles.sh		(for user, group, and public).
#
# Run this script on the command line by typing
#	./CopyOutputFiles.sh
#**************************************************************************************************************

#------------------------------------------------------------------------------------------------------------------------------------------
# e.g. mgPath = /work/trenton/MadGraph5_v1_4_5
# e.g. newLheDir = QBallLHE
#------------------------------------------------------------------------------------------------------------------------------------------
# Initialize arrays
chargeString=("2" "3" "4" "5" "6")								# Charge array
#chargeString=("1.0" "0.7" "0.3")
massString=("050" "100" "200" "300" "400" "500" "600")			# Mass array
#massString=("050" "100" "250")			# Mass array
runString=("01" "02")					# Runs for each event

# Define path to MadGraph directory and choose name of directory that holds all copied .lhe files
mgPath="/work/trenton/MadGraph5_v1_4_5"
newLheDir="QBallLHE"
#newLheDir="QBallLHE_lowcharge"
#newLheDir="QBallLHE_lowcharge_b4000"
#------------------------------------------------------------------------------------------------------------------------------------------

# Create directory that holds all copied .lhe files
mkdir $mgPath"/"$newLheDir

#Cycle over charges
for i in ${chargeString[@]}; do					# Can use @ or *
	# Cycle over masses
	for j in ${massString[@]}; do
		#Cycle over runs
		for k in ${runString[@]}; do
			
			#------------------------------------------------------------------------------------------------------------------
			# e.g. sampleIdentifier = QBProd1.0_m050
			# e.g. eventPath = /work/trenton/MadGraph5_v1_4_5/QBProd1.0/QBProd1.0_m050/Events
			#------------------------------------------------------------------------------------------------------------------
			sampleIdentifier="QBProd"$i"_m"$j
			#sampleIdentifier="QBProd"$i"_m"$j"_b4000"
			eventPath=$mgPath"/QBProd"$i"/"$sampleIdentifier"/Events"
			#------------------------------------------------------------------------------------------------------------------
			
			# Gunzip and untar .lhe file
			# e.g. oldLheFilePath = run_01/unweighted_events.lhe
			cd $eventPath
			oldLheFilePath="run_"$k"/unweighted_events.lhe"
			tar xvfz $oldLheFilePath".tar.gz"
			
			# Copy, move, and rename .lhe file
			# e.g. newLheFilePath = /work/trenton/MadGraph5_v1_4_5/QBallLHE
			#					/unweighted_events_QBProd1.0_m050_run_01.lhe			
			newLheFile="unweighted_events_"$sampleIdentifier"_run_"$k".lhe"
			newLheFilePath=$mgPath"/"$newLheDir"/"$newLheFile
			cp $oldLheFilePath $newLheFilePath
						
			# Copy ROOT files from directory containing same-Event ROOT files
			# (not including subfolders) to "Events" directory
			# e.g. oldRootFilePath = {...}/Events/run_01/unweighted_events.root
			# e.g. newRootFilePath = {...}/unweighted_events_run_01.root		
			oldRootFilePath="run_"$k"/unweighted_events.root"
			newRootFilePath="unweighted_events_run_"$k".root"
			cp $oldRootFilePath $newRootFilePath
			 
		done			# Runs
	done				# Masses
done					# Charges

# Tar and gzip directory that holds all copied .lhe files
cd $mgPath
tar cvfz $newLheDir".tar.gz" $newLheDir





